version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bookstore_mysql
    environment:
      MYSQL_ROOT_PASSWORD: trong123
      MYSQL_DATABASE: bookstore
      MYSQL_USER: bookstore_user
      MYSQL_PASSWORD: bookstore_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/bookstore.sql:/docker-entrypoint-initdb.d/bookstore.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local
